/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'text' : string,
  'sender' : string,
  'timestamp' : bigint,
}
export interface User {
  'displayName' : string,
  'sessionToken' : string,
  'lastActive' : bigint,
}
export interface _SERVICE {
  'createRoom' : ActorMethod<[], string>,
  'getActiveUsers' : ActorMethod<[string], Array<User>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'joinRoom' : ActorMethod<[string, [] | [string]], string>,
  'leaveRoom' : ActorMethod<[string, string], undefined>,
  'ping' : ActorMethod<[string, string], undefined>,
  'roomExists' : ActorMethod<[string], boolean>,
  'sendMessage' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];