/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const User = IDL.Record({
  'displayName' : IDL.Text,
  'sessionToken' : IDL.Text,
  'lastActive' : IDL.Int,
});
export const Message = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'createRoom' : IDL.Func([], [IDL.Text], []),
  'getActiveUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'joinRoom' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
  'leaveRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'ping' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'roomExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const User = IDL.Record({
    'displayName' : IDL.Text,
    'sessionToken' : IDL.Text,
    'lastActive' : IDL.Int,
  });
  const Message = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'createRoom' : IDL.Func([], [IDL.Text], []),
    'getActiveUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'joinRoom' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
    'leaveRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'ping' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'roomExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };